import type { Metadata } from "next";
import { Gilda_Display, Jost } from "next/font/google";
import "./globals.css";

const gilda = Gilda_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-gilda",
});
const jost = Jost({ subsets: ["latin"], variable: "--font-jost" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gilda.variable} ${jost.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
